import React from 'react';
import LeadForm from './LeadForm';
import { CheckCircleIcon, SparklesIcon, ChartBarIcon, RocketLaunchIcon } from './Icons';

interface LandingPageProps {
  onSuccess: (email: string) => void;
}

const LandingPage: React.FC<LandingPageProps> = ({ onSuccess }) => {
  const logoUrl = "https://raw.githubusercontent.com/stackblitz/stackblitz-images/main/chatbot-boy-logo.png";

  return (
    <div className="flex flex-col">
      {/* Header */}
      <header className="py-4 px-4 sm:px-8 max-w-7xl mx-auto w-full flex justify-between items-center bg-white/80 backdrop-blur sticky top-0 z-50">
        <div className="flex items-center space-x-3 cursor-pointer" onClick={() => window.scrollTo({top: 0, behavior: 'smooth'})}>
          <img src={logoUrl} alt="Chatbot Boy AI Logo" className="h-10 w-auto object-contain" />
          <span className="text-xl font-bold tracking-tight text-gray-800">Chatbot Boy AI</span>
        </div>
        <nav className="hidden md:flex space-x-8 text-sm font-semibold text-gray-600">
          <a href="#form-section" className="hover:text-blue-600 transition">Get Roadmap</a>
        </nav>
      </header>

      {/* Hero Section */}
      <section className="pt-16 pb-24 px-4 sm:px-8 max-w-7xl mx-auto grid lg:grid-cols-2 gap-16 items-center">
        <div className="space-y-8 animate-fade-in">
          <div className="inline-flex items-center space-x-2 bg-blue-50 text-blue-700 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider">
            <span>Free for a limited time</span>
          </div>
          <h1 className="text-4xl md:text-5xl lg:text-7xl font-extrabold text-gray-900 leading-tight">
            Get Your Free <span className="text-blue-600">AI Roadmap</span>
          </h1>
          <p className="text-lg md:text-xl text-gray-600 max-w-2xl leading-relaxed">
            Discover how Chatbot Boy AI can automate your business processes. Custom analysis in minutes—no sales call required.
          </p>
          
          <div className="space-y-4">
            <div className="flex items-start space-x-3">
              <CheckCircleIcon className="w-6 h-6 text-green-500 mt-1" />
              <div>
                <p className="font-semibold text-gray-800">Custom Automation Roadmap</p>
                <p className="text-sm text-gray-500">Tailored specifically to your manual workflows.</p>
              </div>
            </div>
            <div className="flex items-start space-x-3">
              <CheckCircleIcon className="w-6 h-6 text-green-500 mt-1" />
              <div>
                <p className="font-semibold text-gray-800">ROI Estimation & Tool Recommendations</p>
                <p className="text-sm text-gray-500">Save time and money with smart tool selection.</p>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-3xl shadow-2xl p-8 sm:p-10 border border-gray-100 relative overflow-hidden" id="form-section">
          <h2 className="text-2xl font-bold text-gray-900 mb-6">Analyze Your Process</h2>
          <LeadForm onSuccess={onSuccess} />
          <p className="mt-4 text-center text-xs text-gray-400">
            Secure processing by Chatbot Boy AI.
          </p>
        </div>
      </section>

      {/* Features Section */}
      <section className="bg-white py-24 px-4 sm:px-8 border-y border-gray-100">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900">What You'll Receive in Your Inbox</h2>
            <p className="mt-4 text-gray-600">Comprehensive report generated by our proprietary AI agents.</p>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            <div className="p-8 rounded-2xl bg-gray-50 border border-gray-100 transition hover:shadow-md">
              <ChartBarIcon className="w-12 h-12 text-blue-600 mb-6" />
              <h3 className="font-bold text-xl mb-3">ROI Estimation</h3>
              <p className="text-gray-600">Detailed breakdown of potential cost savings and efficiency gains.</p>
            </div>
            <div className="p-8 rounded-2xl bg-gray-50 border border-gray-100 transition hover:shadow-md">
              <RocketLaunchIcon className="w-12 h-12 text-blue-600 mb-6" />
              <h3 className="font-bold text-xl mb-3">Actionable Steps</h3>
              <p className="text-gray-600">Step-by-step implementation plan from manual to automated.</p>
            </div>
            <div className="p-8 rounded-2xl bg-gray-50 border border-gray-100 transition hover:shadow-md">
              <SparklesIcon className="w-12 h-12 text-blue-600 mb-6" />
              <h3 className="font-bold text-xl mb-3">Tool Selection</h3>
              <p className="text-gray-600">Best AI tools (n8n, Zapier, LLMs) for your specific needs.</p>
            </div>
          </div>
        </div>
      </section>
      
      {/* Footer */}
      <footer className="bg-[#0f172a] text-gray-400 py-16 px-4 sm:px-8">
        <div className="max-w-7xl mx-auto grid md:grid-cols-2 gap-12">
          <div>
            <div className="flex items-center space-x-3 text-white mb-6">
              <img src={logoUrl} alt="Chatbot Boy AI" className="h-10 w-auto" />
              <span className="text-2xl font-bold">Chatbot Boy AI</span>
            </div>
            <p className="text-sm max-w-sm leading-relaxed">
              Helping businesses unlock their potential through intelligent automation and expert consulting.
            </p>
          </div>
          <div className="flex flex-col md:items-end justify-center space-y-4">
            <div className="flex flex-wrap gap-8 text-sm">
              <a href="#privacy-policy" className="hover:text-white transition">Privacy Policy</a>
              <a href="#terms-of-service" className="hover:text-white transition">Terms of Service</a>
              <a href="mailto:info@chatbotboy.ai" className="hover:text-white transition">Contact Us</a>
            </div>
            <div className="text-xs pt-4 border-t border-gray-800 w-full md:w-auto text-center md:text-right">
              © 2026 Chatbot Boy AI. All rights reserved.
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;